---
title: "Gold ETF Prices, Daily"
output: html_document
---

```{r}

```


```{r, comment=NA }

```

```{r, message=F}
# load libraries
library(fGarch)
library(tseries)
library(forecast)
library(fpp)
```

# Data

```{r, comment=NA }
# Load data
gold <- read.csv("project_gold_gld_daily.txt",header=F, sep=",", as.is=TRUE, skip=54, col.names = c("Date", "Value"))

# Set as time-series
gold.ts0 <- ts(gold$Value)

# Remove last 6 observations
gold.ts <- head(gold.ts0,-6)
length(gold.ts0)
length(gold.ts)


```

### Original time series

```{r, comment=NA }
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
plot(gold.ts, main="gold.ts")
acf(gold.ts, lag.max = 30)
pacf(gold.ts, lag.max=30)
```

###First differences

```{r, comment=NA }
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
plot(diff(gold.ts), main="diff(gold.ts)")
acf(diff(gold.ts), lag.max = 30)
pacf(diff(gold.ts), lag.max=30)
```

###Differences of the log

```{r, comment=NA }
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
plot(diff(log(gold.ts)), main="diff(log(gold.ts))")
acf(diff(log(gold.ts)), lag.max = 30)
pacf(diff(log(gold.ts)), lag.max=30)
```

# ARIMA

###Auto-arima...

```{r, comment=NA }
auto.arima(diff(log(gold.ts)))
```

```{r, comment=NA }
auto.arima(diff(gold.ts))
```

# ARCH-GARCH

```{r, comment=NA }
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
plot(diff(log(gold.ts))^2, main="diff(log(gold.ts))^2")
acf(diff(log(gold.ts))^2, lag.max = 30)
pacf(diff(log(gold.ts))^2, lag.max=30)
```

## Models with no ARMA process and ARCH(n)

### ARCH(1)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(1,0), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### ARCH(2)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(2,0), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### ARCH(3)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(3,0), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### ARCH(4)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(4,0), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

## Models with no ARMA process and GARCH(n,m)

### GARCH(1,1)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(1,1), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### GARCH(1,2)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(1,2), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### GARCH(2,1)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(2,1), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

### GARCH(2,2)

```{r, comment=NA }
garch.fit <- garchFit(formula=~garch(2,2), data=diff(log(gold.ts)), trace=FALSE)
summary(garch.fit)
```

# ARMA-GARCH

```{r, comment=NA }
fit <- garchFit(formula=~arma(1,0)+garch(1,1), data=diff(log(gold.ts)), trace=F)
summary(fit)
```

```{r, comment=NA }
fit <- garchFit(formula=~arma(1,1)+garch(1,1), data=diff(log(gold.ts)), trace=F)
summary(fit)
```

```{r, comment=NA }
fit <- garchFit(formula=~arma(0,1)+garch(1,1), data=diff(log(gold.ts)), trace=F)
summary(fit)
```




